---
title: "report-COVID-19"
author: "Thomas Gredig"
date: "7/12/2020"
output: 
  rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message  = FALSE)
library(ggplot2)
library(ggrepel)
library(ggthemes)
library(reshape2)
library(knitr)
library(dplyr)
library(lubridate)
library(zoo)
scientific_10 <- function(x) {
    xout <- gsub("1e", "10^{", format(x),fixed=TRUE)
    xout <- gsub("{-0", "{-", xout,fixed=TRUE)
    xout <- gsub("{+", "{", xout,fixed=TRUE)
    xout <- gsub("{0", "{", xout,fixed=TRUE)
    xout <- paste(xout,"}",sep="")
    return(parse(text=xout))
}
scale_y_log10nice <- function(name=NULL,omag=seq(-10,20),...) {
    breaks10 <- 10^omag
    scale_y_log10(name,breaks=breaks10,labels=scientific_10(breaks10),...)
}
scale_x_log10nice <- function(name=NULL,omag=seq(-10,20),...) {
    breaks10 <- 10^omag
    scale_x_log10(name,breaks=breaks10,labels=scientific_10(breaks10),...)
}
```



# COVID-19

We are comparing the growth rates in different regions.

The data is from the [CSSE COVID-19 Dataset](https://github.com/CSSEGISandData/COVID-19).

Projections based on [SIR models](https://www.maa.org/press/periodicals/loci/joma/the-sir-model-for-spread-of-disease-the-differential-equation-model) from [HealthData](https://covid19.healthdata.org/projections).


```{r}
# return population of a country
dc = read.csv('data/population-by-country-2015.csv', stringsAsFactors = FALSE)
getPopulation <- function(countryName) {
  countryName = gsub('\\*','',countryName)
  if (countryName=='US') { countryName='United States' }
  if (countryName=='Czechia') { countryName ='Czech Republic'}
  if (countryName=='Korea, South') { countryName = 'South Korea' }
  mc = which(dc$country==countryName)
  if (length(mc)>= 1) { p = dc$p[mc] } else { p=1e12 }
  p/1e6
}
```

```{r}
# load confirmed cases
path.series = 'csse_covid_19_data/csse_covid_19_time_series'
file.list = dir(path.series, pattern='csv$')
filename = 'time_series_covid19_confirmed_global.csv' 
f = file.path(path.series, filename)
d = read.csv(f)
d1 = d[,-c(1,3,4)]
m1 = melt(d1)
names(m1) = c('Region','Date','Confirmed')
m1$Date = gsub('^X','',as.character(levels(m1$Date)[m1$Date]))
m1$Date = as.Date(m1$Date, format='%m.%d.%y')
m1=m1[order(m1$Region),]
m1$Confirmed.PerMio = unlist(by(m1, m1$Region, 
                                function(x) {x$Confirmed / getPopulation(levels(x$Region)[x$Region])}))
m1$Confirmed.PerMio.3Day = m1$Confirmed.PerMio.3Day
```


## Confirmed COVID-19 Cases

Regions with more than 5,000 confirmed cases increased rapidly from a few to many.

```{r}
AVG.DAYS=7
m1 %>%
  filter(Region == 'US' | Region=='Korea, South' | Region=='Italy' | Region == 'Germany' |
           Region == 'Switzerland' | Region == 'Singapore') %>%
  mutate(Confirmed.PerMio.New = c(0,diff(Confirmed.PerMio))) %>%
  mutate(Confirmed.3DayMean = rollmean(Confirmed.PerMio.New, k=AVG.DAYS, fill=NA)) %>%
  filter(Date >= as.Date('2020-03-02')) %>%
  filter(Date < Sys.Date()-AVG.DAYS) %>%
  ggplot(aes(Date,Confirmed.3DayMean, color=Region)) + 
  ylab('confirmed new cases per million') +
  geom_line(size=1.5) +
  #scale_y_continuous(breaks=c(0:5*250)) + 
  scale_x_date() +
  ggtitle('Confirmed new COVID-19 Cases per Million') + 
  theme(plot.background = element_rect(fill="darkslateblue",colour='white'),
        panel.background  = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text = element_text(color='white'),
        legend.background = element_blank(),
        legend.key = element_rect(fill="darkslateblue",colour='darkslateblue'),
        legend.text = element_text(colour = "white"),
        title = element_text(colour = "white"),
        axis.ticks.length.x.bottom = 
        )
```



